### PR TITLE
Issue #274

### PR DESCRIPTION
**Pull request by DavidMcCann-NOC**
Actions for seastar project housekeeping

### CODE REVIEW

**Comment by DavidMcCann-NOC** [comment]
It looks like three of the notebooks i moved to /gmfs are conflicting - it might be because they don't exist on main anymore?

**Comment by ACHMartin** [comment]
> It looks like three of the notebooks i moved to /gmfs are conflicting - it might be because they don't exist on main anymore?

I think I already moved them on the "main". Please discard your modification on these files (keep what there is on the main)

**Comment by DavidMcCann-NOC** [comment]
> To resolve the conflict: For the conflicted Notebooks, please keep what there is on the main and don't merge your changes For tools.py, you will have to dig a bit to see changes.
> 
> It was a big Merge Request with different subject. Not easy to review (and to monitor if we have too in the futur). Small is beautiful ;)
> 
> Otherwise, happy to merge

Sorry, I'm a bit confused - so keep all of the notebooks on main? If so I'm not sure how to un-merge my changes

**Comment by ACHMartin** [comment]
> > To resolve the conflict: For the conflicted Notebooks, please keep what there is on the main and don't merge your changes For tools.py, you will have to dig a bit to see changes.
> > It was a big Merge Request with different subject. Not easy to review (and to monitor if we have too in the futur). Small is beautiful ;)
> > Otherwise, happy to merge
> 
> Sorry, I'm a bit confused - so keep all of the notebooks on main? If so I'm not sure how to un-merge my changes

you need to rebase from the main and solve the conflicts locally on your branch. Once the conflicts are solved you can push and conflicts should be resolved

**Pull request closed without merging**
